// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tsrffpdecdlnqehrmdkj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzcmZmcGRlY2RsbnFlaHJtZGtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMDQyNzIsImV4cCI6MjA2MTY4MDI3Mn0.jF2f0NMw3GltUfLbzq5NURlX_KBex6-o5jqbHAaNn84";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);